services:
  - type: web
    name: dgt-sounds
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve dist -s -l $PORT
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
